OpenGOO: BackGroundWidget Class Reference
BackGroundWidget Class Reference
#include <backgroundwidget.h>
Public Slots
void translated (QPoint p)
void setTarget (Target *target)
void addGround (Ground *ground)
void addBackGround (BackGround *bg)
void setScale (float scale)
void setLimit (QRect limit)
void clear ()
Public Member Functions
BackGroundWidget (QWidget *parent=0)
Protected Member Functions
void paintEvent (QPaintEvent *)
Private Attributes
QList< Ground * > ground
QList< BackGround * > background
Target * target
QRadialGradient bgColor
QPoint translation
QRect limit
float scale
Detailed Description
Definition at line 12 of file backgroundwidget.h.
Constructor & Destructor Documentation
BackGroundWidget::BackGroundWidget (QWidget * parent = 0) [explicit]
Definition at line 6 of file backgroundwidget.cpp.
References bgColor, scale, target, and translation.
Member Function Documentation
void BackGroundWidget::paintEvent (QPaintEvent * e) [protected]
Definition at line 24 of file backgroundwidget.cpp.
References background, bgColor, ground, Target::paint(), scale, target, and translation.
void BackGroundWidget::translated (QPoint p) [slot]
Definition at line 62 of file backgroundwidget.cpp.
References translation.
Referenced by Level::moveDown(), Level::moveLeft(), Level::moveOf(), Level::moveRight(), Level::moveUp(), and Level::setLimit().
void BackGroundWidget::setTarget (Target * target) [inline, slot]
Definition at line 33 of file backgroundwidget.h.
References target.
Referenced by Level::setTarget().
void BackGroundWidget::addGround (Ground * ground) [slot]
Definition at line 57 of file backgroundwidget.cpp.
References Ground::contains().
Referenced by Level::setGround().
void BackGroundWidget::addBackGround (BackGround * bg) [slot]
Definition at line 52 of file backgroundwidget.cpp.
References background.
Referenced by Level::addBGShape().
void BackGroundWidget::setScale (float scale) [inline, slot]
Definition at line 38 of file backgroundwidget.h.
References scale.
Referenced by Level::setLimit(), and Level::wheelEvent().
void BackGroundWidget::setLimit (QRect limit) [slot]
Definition at line 69 of file backgroundwidget.cpp.
References bgColor, and limit.
Referenced by Level::setLimit().
void BackGroundWidget::clear () [slot]
Definition at line 80 of file backgroundwidget.cpp.
References background, ground, scale, and translation.
Referenced by Level::clean().
Member Data Documentation
QList<Ground *> BackGroundWidget::ground [private]
Definition at line 22 of file backgroundwidget.h.
Referenced by clear(), and paintEvent().
QList<BackGround*> BackGroundWidget::background [private]
Definition at line 23 of file backgroundwidget.h.
Referenced by addBackGround(), clear(), and paintEvent().
Target* BackGroundWidget::target [private]
Definition at line 24 of file backgroundwidget.h.
Referenced by BackGroundWidget(), paintEvent(), and setTarget().
QRadialGradient BackGroundWidget::bgColor [private]
Definition at line 25 of file backgroundwidget.h.
Referenced by BackGroundWidget(), paintEvent(), and setLimit().
QPoint BackGroundWidget::translation [private]
Definition at line 26 of file backgroundwidget.h.
Referenced by BackGroundWidget(), clear(), paintEvent(), and translated().
QRect BackGroundWidget::limit [private]
Definition at line 27 of file backgroundwidget.h.
Referenced by setLimit().
float BackGroundWidget::scale [private]
Definition at line 28 of file backgroundwidget.h.
Referenced by BackGroundWidget(), clear(), paintEvent(), and setScale().
The documentation for this class was generated from the following files:
backgroundwidget.h
backgroundwidget.cpp