OpenGOO: PlaySoundThread Class Reference
PlaySoundThread Class Reference
The PlaySoundThread class is a thread that manages the background song.
#include <playsoundthread.h>
Public Member Functions
PlaySoundThread (QObject *parent=0)
void run ()
void quit ()
void stopSong ()
void pauseSong ()
void startSong ()
Private Attributes
SoundSystem * soundSystem
ALuint soundSource
Detailed Description
The PlaySoundThread class is a thread that manages the background song.
Definition at line 13 of file playsoundthread.h.
Constructor & Destructor Documentation
PlaySoundThread::PlaySoundThread (QObject * parent = 0) [explicit]
Definition at line 4 of file playsoundthread.cpp.
Member Function Documentation
void PlaySoundThread::run ()
The soundSystem object is here initialized and the song is loaded.
Definition at line 9 of file playsoundthread.cpp.
References SoundSystem::initialize(), SoundSystem::playOGG(), soundSystem, and sSystem.
void PlaySoundThread::quit ()
Deletes the thread.
Definition at line 52 of file playsoundthread.cpp.
References soundSystem, and stopSong().
Referenced by Level::clean().
void PlaySoundThread::stopSong ()
Stops the song.
Definition at line 24 of file playsoundthread.cpp.
References SoundSystem::getSource(), soundSource, soundSystem, and SoundSystem::stopSource().
Referenced by quit().
void PlaySoundThread::pauseSong ()
Puts the song in pause.
Definition at line 34 of file playsoundthread.cpp.
References SoundSystem::getSource(), SoundSystem::pauseSource(), soundSource, and soundSystem.
Referenced by Level::clickMute(), Level::keyReleaseEvent(), and Level::mouseReleaseEvent().
void PlaySoundThread::startSong ()
Plays the song.
Definition at line 43 of file playsoundthread.cpp.
References SoundSystem::getSource(), SoundSystem::playSource(), soundSource, and soundSystem.
Referenced by Level::clickMute(), Level::keyReleaseEvent(), and Level::resume().
Member Data Documentation
SoundSystem* PlaySoundThread::soundSystem [private]
Definition at line 17 of file playsoundthread.h.
Referenced by pauseSong(), quit(), run(), startSong(), and stopSong().
ALuint PlaySoundThread::soundSource [private]
Definition at line 18 of file playsoundthread.h.
Referenced by pauseSong(), startSong(), and stopSong().
The documentation for this class was generated from the following files:
playsoundthread.h
playsoundthread.cpp