OpenGOO: Joint Class Reference
Joint Class Reference
#include <joint.h>
Signals
void destroyJoint (Joint *j)
Public Member Functions
Joint (Goo *a, Goo *b, b2World *world, bool child=false, QObject *parent=0)
virtual void paint (QPainter &p)
void paintDebug (QPainter &p)
b2Joint * getJoint ()
bool has (Goo *a, Goo *b)
JointType getType ()
Goo * goo (bool id)
QRect boundingRect ()
QPolygon boundingPoly ()
virtual void status ()
Protected Member Functions
virtual void initialize (b2World *world)
Protected Attributes
JointType type
b2Joint * joint
Goo * a
Goo * b
Private Member Functions
void drawLines (QPainter &p)
Private Attributes
float animationValue
int counter
Detailed Description
Definition at line 10 of file joint.h.
Constructor & Destructor Documentation
Joint::Joint (Goo * a, Goo * b, b2World * world, bool child = false, QObject * parent = 0) [explicit]
Definition at line 7 of file joint.cpp.
References a, animationValue, b, counter, initialize(), NORMAL, and type.
Member Function Documentation
void Joint::paint (QPainter & p) [virtual]
Reimplemented in RopeJoint.
Definition at line 28 of file joint.cpp.
References a, animationValue, b, counter, drawLines(), Goo::getColor(), and Goo::getPPosition().
void Joint::paintDebug (QPainter & p)
Definition at line 76 of file joint.cpp.
References joint, realStep, and toPoint().
b2Joint* Joint::getJoint () [inline]
Definition at line 18 of file joint.h.
References joint.
bool Joint::has (Goo * a, Goo * b)
Definition at line 130 of file joint.cpp.
JointType Joint::getType () [inline]
Definition at line 22 of file joint.h.
References type.
Goo * Joint::goo (bool id)
Definition at line 136 of file joint.cpp.
References a, and b.
Referenced by Level::anchorToJoint().
QRect Joint::boundingRect ()
Definition at line 141 of file joint.cpp.
References a, b, and Goo::boundingRect().
QPolygon Joint::boundingPoly ()
Definition at line 147 of file joint.cpp.
References a, b, and Goo::boundingRect().
void Joint::status () [virtual]
Reimplemented in RopeJoint.
Definition at line 85 of file joint.cpp.
References a, SoundSystem::addSource(), b, SoundSystem::createSource(), destroyJoint(), Goo::destroyLink(), Goo::getPPosition(), Goo::getRadius(), Goo::isDragging(), joint, SoundSystem::playSource(), realStep, SoundSystem::setPosition(), SoundSystem::setVolume(), and sSystem.
void Joint::initialize (b2World * world) [protected, virtual]
Reimplemented in RopeJoint.
Definition at line 19 of file joint.cpp.
References a, b, Goo::getBody(), Goo::getVPosition(), and joint.
Referenced by Joint().
void Joint::drawLines (QPainter & p) [private]
Definition at line 116 of file joint.cpp.
References a, b, joint, and toPoint().
Referenced by paint().
void Joint::destroyJoint (Joint * j) [signal]
Referenced by RopeJoint::paint(), and status().
Member Data Documentation
JointType Joint::type [protected]
Definition at line 31 of file joint.h.
Referenced by getType(), Joint(), and RopeJoint::RopeJoint().
b2Joint* Joint::joint [protected]
Definition at line 33 of file joint.h.
Referenced by drawLines(), getJoint(), RopeJoint::initialize(), initialize(), RopeJoint::paint(), paintDebug(), and status().
Goo* Joint::a [protected]
Definition at line 34 of file joint.h.
Referenced by boundingPoly(), boundingRect(), drawLines(), goo(), RopeJoint::initialize(), initialize(), Joint(), paint(), RopeJoint::paint(), and status().
Goo * Joint::b [protected]
Definition at line 34 of file joint.h.
Referenced by boundingPoly(), boundingRect(), drawLines(), goo(), RopeJoint::initialize(), initialize(), Joint(), paint(), RopeJoint::paint(), and status().
float Joint::animationValue [private]
Definition at line 38 of file joint.h.
Referenced by Joint(), and paint().
int Joint::counter [private]
Definition at line 39 of file joint.h.
Referenced by Joint(), and paint().
The documentation for this class was generated from the following files:
joint.h
joint.cpp