OpenGOO: BalloonGoo Class Reference
BalloonGoo Class Reference
#include <balloongoo.h>
Public Slots
void paint (QPainter &p)
void paintDebug (QPainter &p)
void update ()
Public Member Functions
BalloonGoo (b2World *world, QPoint p=QPoint(0, 0), int radius=15, QObject *parent=0)
void drag ()
bool createLink (Goo *goo)
bool destroyLink (Goo *goo)
bool isDragable ()
Private Attributes
b2Vec2 force
bool active
int rx
int ry
int stdRadius
Detailed Description
Definition at line 7 of file balloongoo.h.
Constructor & Destructor Documentation
BalloonGoo::BalloonGoo (b2World * world, QPoint p = QPoint(0,0), int radius = 15, QObject * parent = 0)
Definition at line 10 of file balloongoo.cpp.
References BALOON, Goo::body, DynamicGoo::color, Goo::distanceToJoint, Goo::guestN, Goo::maxGuest, Goo::maxJoints, Goo::radius, rx, ry, DynamicGoo::secondaryColor, stdRadius, DynamicGoo::stickable, and Goo::type.
Member Function Documentation
void BalloonGoo::drag () [virtual]
Reimplemented from Goo.
Definition at line 124 of file balloongoo.cpp.
References dragInfo::aForce, Goo::body, destroyLink(), Goo::dragging, dragInfo::gScale, Goo::hasJoint(), Goo::info, Goo::links, Goo::onGround, dragInfo::speed, and Goo::stopFollow().
bool BalloonGoo::createLink (Goo * goo) [virtual]
Reimplemented from Goo.
Definition at line 71 of file balloongoo.cpp.
References active, Goo::body, Goo::following, force, Goo::links, Goo::maxJoints, Goo::nJoints(), Goo::radius, rx, ry, Goo::sleeping, and Goo::stopFollow().
bool BalloonGoo::destroyLink (Goo * goo) [virtual]
Reimplemented from Goo.
Definition at line 99 of file balloongoo.cpp.
References active, Goo::body, Goo::destroyJoint(), Goo::destroyLink(), Goo::hasJoint(), Goo::isDragging(), Goo::isLinked(), Goo::links, Goo::radius, rx, ry, and stdRadius.
Referenced by drag().
bool BalloonGoo::isDragable () [inline, virtual]
Reimplemented from DynamicGoo.
Definition at line 14 of file balloongoo.h.
References Goo::isSleeping().
void BalloonGoo::paint (QPainter & p) [virtual, slot]
Reimplemented from DynamicGoo.
Definition at line 31 of file balloongoo.cpp.
References active, Goo::body, DynamicGoo::color, Goo::dragging, Goo::getRadius(), Goo::radius, rx, ry, Goo::selected, and toPoint().
void BalloonGoo::paintDebug (QPainter & p) [virtual, slot]
Reimplemented from DynamicGoo.
Definition at line 145 of file balloongoo.cpp.
References Goo::body, and Goo::getPPosition().
void BalloonGoo::update () [virtual, slot]
Reimplemented from DynamicGoo.
Definition at line 170 of file balloongoo.cpp.
References active, Goo::body, Goo::checkForNeighbors(), force, Goo::getPPosition(), Goo::isSleeping(), and DynamicGoo::moveToTarget().
Member Data Documentation
b2Vec2 BalloonGoo::force [private]
Definition at line 20 of file balloongoo.h.
Referenced by createLink(), and update().
bool BalloonGoo::active [private]
Definition at line 21 of file balloongoo.h.
Referenced by createLink(), destroyLink(), paint(), and update().
int BalloonGoo::rx [private]
Reimplemented from DynamicGoo.
Definition at line 22 of file balloongoo.h.
Referenced by BalloonGoo(), createLink(), destroyLink(), and paint().
int BalloonGoo::ry [private]
Reimplemented from DynamicGoo.
Definition at line 22 of file balloongoo.h.
Referenced by BalloonGoo(), createLink(), destroyLink(), and paint().
int BalloonGoo::stdRadius [private]
Definition at line 23 of file balloongoo.h.
Referenced by BalloonGoo(), and destroyLink().
The documentation for this class was generated from the following files:
balloongoo.h
balloongoo.cpp