OpenGOO: DynamicGoo Class Reference
DynamicGoo Class Reference
#include <dynamicgoo.h>
Public Slots
void paint (QPainter &p)
void paintDebug (QPainter &p)
void neighborsFound ()
void update ()
Public Member Functions
DynamicGoo (b2World *world, QPoint p=QPoint(0, 0), int radius=15, QObject *parent=0)
void catched ()
void lost ()
void contactGround ()
void contactGround (QPoint p)
void unstick ()
bool isDragable ()
QColor getColor ()
Protected Member Functions
void moveToTarget ()
Protected Attributes
QColor color
QColor secondaryColor
bool stickable
Private Attributes
b2World * world
int speed
bool sticked
QList< QPair< unsigned int,
unsigned int > > sources
int counter
int rx
int ry
bool eye
int eyeSizeR
int eyeSizeL
int delay
int angle
Detailed Description
Definition at line 14 of file dynamicgoo.h.
Constructor & Destructor Documentation
DynamicGoo::DynamicGoo (b2World * world, QPoint p = QPoint(0,0), int radius = 15, QObject * parent = 0)
Definition at line 14 of file dynamicgoo.cpp.
References Goo::body, color, counter, delay, Goo::dragable, DYNAMIC, eye, eyeSizeL, eyeSizeR, Goo::maxJoints, Goo::moovable, rx, ry, secondaryColor, speed, stickable, sticked, toVec(), Goo::type, and world.
Member Function Documentation
void DynamicGoo::catched () [inline, virtual]
Reimplemented from Goo.
Definition at line 19 of file dynamicgoo.h.
References speed.
void DynamicGoo::lost () [inline, virtual]
Reimplemented from Goo.
Definition at line 22 of file dynamicgoo.h.
References speed.
void DynamicGoo::contactGround () [virtual]
Implements Goo.
Definition at line 380 of file dynamicgoo.cpp.
References Goo::body, SoundSystem::createSource(), Goo::dragging, Goo::fallDown(), Goo::getPPosition(), Goo::groundPoint, Goo::hasJoint(), Goo::isDragging(), Goo::isSleeping(), Goo::nextTargetPlease(), Goo::onGround, SoundSystem::playSource(), Goo::prevTarget, Goo::radius, SoundSystem::setPitch(), SoundSystem::setPosition(), SoundSystem::setVolume(), Goo::sleeping, sources, sSystem, Goo::stopDragging(), and Goo::target.
void DynamicGoo::contactGround (QPoint p) [virtual]
Implements Goo.
Definition at line 420 of file dynamicgoo.cpp.
References Goo::body, Goo::createSticky(), Goo::dragging, Goo::fallDown(), Goo::getPPosition(), Goo::groundPoint, Goo::hasJoint(), Goo::isDragging(), Goo::nextTargetPlease(), Goo::onGround, Goo::sleeping, stickable, sticked, Goo::stopDragging(), and Goo::target.
void DynamicGoo::unstick () [inline]
Definition at line 27 of file dynamicgoo.h.
References sticked.
Referenced by Level::destroySticky().
bool DynamicGoo::isDragable () [inline, virtual]
Reimplemented from Goo.
Reimplemented in BalloonGoo, and RemovableGoo.
Definition at line 31 of file dynamicgoo.h.
References Goo::hasJoint(), and Goo::isSleeping().
Referenced by paint().
QColor DynamicGoo::getColor () [inline, virtual]
Implements Goo.
Definition at line 34 of file dynamicgoo.h.
References secondaryColor.
void DynamicGoo::moveToTarget () [protected]
Reimplemented from Goo.
Definition at line 71 of file dynamicgoo.cpp.
References Goo::body, Goo::distanceToJoint, Goo::drop(), Goo::fallDown(), Goo::falling, Goo::following, Goo::getPPosition(), Goo::getRadius(), Goo::getVPosition(), Goo::groundPoint, Goo::hasJoint(), Goo::isDragging(), Goo::isFalling(), Goo::isLinked(), Goo::isOnGround(), Goo::nextTargetPlease(), Goo::onGround, Goo::prevTarget, Goo::radius, speed, Goo::stopFollow(), Goo::target, and toVec().
Referenced by neighborsFound(), BalloonGoo::update(), and update().
void DynamicGoo::paint (QPainter & p) [virtual, slot]
Implements Goo.
Reimplemented in BalloonGoo.
Definition at line 192 of file dynamicgoo.cpp.
References angle, Goo::body, color, counter, delay, eye, eyeSizeL, eyeSizeR, Goo::getPPosition(), Goo::getRadius(), Goo::hasJoint(), isDragable(), Goo::isDragging(), Goo::isFalling(), Goo::onGround, rx, ry, secondaryColor, Goo::selected, Goo::sleeping, speed, and toPoint().
void DynamicGoo::paintDebug (QPainter & p) [virtual, slot]
Implements Goo.
Reimplemented in BalloonGoo.
Definition at line 297 of file dynamicgoo.cpp.
References Goo::body, Goo::getPPosition(), Goo::hasJoint(), Goo::nJoints(), Goo::prevTarget, Goo::radius, and Goo::target.
void DynamicGoo::neighborsFound () [virtual, slot]
Reimplemented from Goo.
Definition at line 346 of file dynamicgoo.cpp.
References counter, moveToTarget(), and Goo::sleeping.
void DynamicGoo::update () [virtual, slot]
Implements Goo.
Reimplemented in BalloonGoo.
Definition at line 354 of file dynamicgoo.cpp.
References Goo::body, Goo::checkForNeighbors(), SoundSystem::deleteSource(), Goo::getPPosition(), Goo::hasJoint(), Goo::isFalling(), Goo::isSelected(), Goo::isSleeping(), moveToTarget(), sources, SoundSystem::sourceStatus(), and sSystem.
Member Data Documentation
b2World* DynamicGoo::world [private]
Definition at line 38 of file dynamicgoo.h.
Referenced by DynamicGoo().
int DynamicGoo::speed [private]
Definition at line 39 of file dynamicgoo.h.
Referenced by catched(), DynamicGoo(), lost(), moveToTarget(), and paint().
bool DynamicGoo::sticked [private]
Definition at line 40 of file dynamicgoo.h.
Referenced by contactGround(), DynamicGoo(), and unstick().
QList<QPair<unsigned int,unsigned int> > DynamicGoo::sources [private]
Definition at line 42 of file dynamicgoo.h.
Referenced by contactGround(), and update().
int DynamicGoo::counter [private]
Definition at line 46 of file dynamicgoo.h.
Referenced by DynamicGoo(), neighborsFound(), and paint().
int DynamicGoo::rx [private]
Reimplemented in BalloonGoo.
Definition at line 47 of file dynamicgoo.h.
Referenced by DynamicGoo(), and paint().
int DynamicGoo::ry [private]
Reimplemented in BalloonGoo.
Definition at line 47 of file dynamicgoo.h.
Referenced by DynamicGoo(), and paint().
bool DynamicGoo::eye [private]
Definition at line 48 of file dynamicgoo.h.
Referenced by DynamicGoo(), and paint().
int DynamicGoo::eyeSizeR [private]
Definition at line 49 of file dynamicgoo.h.
Referenced by DynamicGoo(), and paint().
int DynamicGoo::eyeSizeL [private]
Definition at line 49 of file dynamicgoo.h.
Referenced by DynamicGoo(), and paint().
int DynamicGoo::delay [private]
Definition at line 50 of file dynamicgoo.h.
Referenced by DynamicGoo(), and paint().
int DynamicGoo::angle [private]
Definition at line 51 of file dynamicgoo.h.
Referenced by paint().
QColor DynamicGoo::color [protected]
Definition at line 55 of file dynamicgoo.h.
Referenced by BalloonGoo::BalloonGoo(), DynamicGoo(), BalloonGoo::paint(), paint(), RemovableGoo::RemovableGoo(), and StickyGoo::StickyGoo().
QColor DynamicGoo::secondaryColor [protected]
Definition at line 56 of file dynamicgoo.h.
Referenced by BalloonGoo::BalloonGoo(), DynamicGoo(), getColor(), paint(), RemovableGoo::RemovableGoo(), and StickyGoo::StickyGoo().
bool DynamicGoo::stickable [protected]
Definition at line 57 of file dynamicgoo.h.
Referenced by BalloonGoo::BalloonGoo(), contactGround(), and DynamicGoo().
The documentation for this class was generated from the following files:
dynamicgoo.h
dynamicgoo.cpp