OpenGOO: Goo Class Reference
Goo Class Reference
#include <goo.h>
Public Slots
virtual void paint (QPainter &p)=0
virtual void paintDebug (QPainter &p)=0
virtual void neighborsFound ()
virtual void update ()=0
Signals
void nextTargetPlease (Goo *previous)
void loseLink (Goo *goo)
void destroyGoo ()
void destroyJoint (Goo *a, Goo *b)
void checkForNeighbors (QPoint p)
void stopDragging ()
void createSticky (QPoint p)
Public Member Functions
Goo (int radius=15, QObject *parent=0)
GooType getType ()
int nJoints ()
int getMaxJoints ()
int getRadius ()
int getGuestNumber ()
int getDistanceToJoint ()
double getStickness ()
int getNumberOf (GooType type)
void countingEnd ()
bool newGuest ()
bool removeGuest ()
bool canHaveGuest ()
Goo * getTarget ()
QRect boundingRect ()
virtual void drag ()
void drop ()
void drop (b2Vec2 speed)
void select (bool s=true)
bool isSelected ()
virtual bool isDragable ()
bool isMoovable ()
bool isFalling ()
bool isDragging ()
bool hasJoint ()
bool canHaveJoint ()
bool isLinked (Goo *goo)
bool isOnGround ()
void setSleep (bool status)
bool isSleeping ()
virtual bool createLink (Goo *goo)
virtual bool destroyLink (Goo *goo)
virtual void contactGround ()=0
virtual void contactGround (QPoint p)=0
virtual void destroyThis ()
virtual QColor getColor ()=0
void setTarget (Goo *goo)
void move (QPoint p)
void jumpTo (QPoint p)
virtual void catched ()
virtual void lost ()
b2Body * getBody ()
b2Vec2 getVPosition ()
b2Vec2 getVPositionScaled ()
QPoint getPPosition ()
QList< Goo * > getLinks ()
Goo * getPrevious ()
Protected Member Functions
void moveToTarget ()
void stopFollow ()
void fallDown ()
Protected Attributes
GooType type
QList< Goo * > links
int radius
dragInfo info
b2Body * body
bool counted
bool dragable
bool moovable
bool falling
bool following
bool dragging
bool onGround
bool selected
bool sleeping
QPoint groundPoint
int minJoints
int maxJoints
int guestN
int maxGuest
int distanceToJoint
double stickness
Goo * target
Goo * prevTarget
Private Slots
void checkForConnection (Goo *goo)
Private Attributes
QPair< unsigned int, unsigned int > scream
Detailed Description
Definition at line 19 of file goo.h.
Constructor & Destructor Documentation
Goo::Goo (int radius = 15, QObject * parent = 0) [explicit]
Definition at line 8 of file goo.cpp.
References dragInfo::aForce, counted, SoundSystem::createSource(), distanceToJoint, dragable, dragging, falling, following, groundPoint, dragInfo::gScale, guestN, info, links, maxGuest, maxJoints, minJoints, moovable, NONE, onGround, prevTarget, radius, scream, selected, sleeping, dragInfo::speed, sSystem, stickness, target, and type.
Member Function Documentation
GooType Goo::getType () [inline]
Definition at line 25 of file goo.h.
References type.
Referenced by Level::createJoints(), Level::makeJoint(), and Level::paintEvent().
int Goo::nJoints () [inline]
Definition at line 29 of file goo.h.
References links.
Referenced by canHaveJoint(), BalloonGoo::createLink(), createLink(), and DynamicGoo::paintDebug().
int Goo::getMaxJoints () [inline]
Definition at line 32 of file goo.h.
References maxJoints.
int Goo::getRadius () [inline]
Definition at line 35 of file goo.h.
References radius.
Referenced by Target::applyImpulse(), DynamicGoo::moveToTarget(), Level::overJoint(), FixedGoo::paint(), BalloonGoo::paint(), DynamicGoo::paint(), FixedGoo::paintDebug(), Level::possibleJoints(), and Joint::status().
int Goo::getGuestNumber () [inline]
Definition at line 38 of file goo.h.
References guestN.
int Goo::getDistanceToJoint () [inline]
Definition at line 42 of file goo.h.
References distanceToJoint.
Referenced by Level::possibleJoints().
double Goo::getStickness () [inline]
Definition at line 46 of file goo.h.
References stickness.
int Goo::getNumberOf (GooType type)
Definition at line 54 of file goo.cpp.
References counted, and links.
void Goo::countingEnd ()
Definition at line 67 of file goo.cpp.
References counted, and links.
bool Goo::newGuest ()
Definition at line 75 of file goo.cpp.
References guestN, and maxGuest.
bool Goo::removeGuest ()
Definition at line 83 of file goo.cpp.
References guestN.
Referenced by setTarget(), and stopFollow().
bool Goo::canHaveGuest ()
Definition at line 91 of file goo.cpp.
References guestN, and maxGuest.
Referenced by Level::anchorToJoint(), and Level::overJoint().
Goo* Goo::getTarget () [inline]
Definition at line 60 of file goo.h.
References target.
Referenced by CollisionListener::PreSolve().
QRect Goo::boundingRect ()
Definition at line 192 of file goo.cpp.
References getPPosition(), and radius.
Referenced by Joint::boundingPoly(), Joint::boundingRect(), and Ground::contains().
void Goo::drag () [virtual]
Reimplemented in BalloonGoo.
Definition at line 210 of file goo.cpp.
References SoundSystem::addSource(), dragInfo::aForce, body, SoundSystem::createSource(), dragging, getPPosition(), dragInfo::gScale, hasJoint(), info, onGround, SoundSystem::playSource(), radius, SoundSystem::setPitch(), SoundSystem::setPosition(), SoundSystem::setVolume(), dragInfo::speed, sSystem, and stopFollow().
Referenced by Level::mousePressEvent(), and Level::timerEvent().
void Goo::drop ()
Definition at line 238 of file goo.cpp.
References dragInfo::aForce, body, dragging, falling, hasJoint(), info, dragInfo::speed, and stopFollow().
Referenced by Level::mouseReleaseEvent(), and DynamicGoo::moveToTarget().
void Goo::drop (b2Vec2 speed)
Definition at line 253 of file goo.cpp.
References body, dragging, falling, and hasJoint().
void Goo::select (bool s = true) [inline]
Definition at line 71 of file goo.h.
References selected.
Referenced by Level::mouseMoveEvent(), and Level::mousePressEvent().
bool Goo::isSelected () [inline]
Definition at line 74 of file goo.h.
References selected.
Referenced by DynamicGoo::update().
virtual bool Goo::isDragable () [inline, virtual]
Reimplemented in DynamicGoo, BalloonGoo, and RemovableGoo.
Definition at line 79 of file goo.h.
References dragable.
bool Goo::isMoovable () [inline]
Definition at line 82 of file goo.h.
References moovable.
Referenced by move().
bool Goo::isFalling () [inline]
Definition at line 85 of file goo.h.
References falling.
Referenced by DynamicGoo::moveToTarget(), DynamicGoo::paint(), CollisionListener::PreSolve(), setTarget(), and DynamicGoo::update().
bool Goo::isDragging () [inline]
Definition at line 88 of file goo.h.
References dragging.
Referenced by Target::applyImpulse(), StickyLink::checkStatus(), DynamicGoo::contactGround(), BalloonGoo::destroyLink(), destroyLink(), DynamicGoo::moveToTarget(), DynamicGoo::paint(), CollisionListener::PostSolve(), and Joint::status().
bool Goo::hasJoint () [inline]
Definition at line 91 of file goo.h.
References links, and radius.
Referenced by Target::applyForce(), Target::applyImpulse(), canHaveJoint(), StickyLink::checkStatus(), DynamicGoo::contactGround(), Level::createJoints(), BalloonGoo::destroyLink(), destroyLink(), BalloonGoo::drag(), drag(), drop(), DynamicGoo::isDragable(), Level::mouseReleaseEvent(), DynamicGoo::moveToTarget(), DynamicGoo::paint(), DynamicGoo::paintDebug(), CollisionListener::PostSolve(), CollisionListener::PreSolve(), and DynamicGoo::update().
bool Goo::canHaveJoint () [inline]
Definition at line 94 of file goo.h.
References hasJoint(), maxJoints, and nJoints().
bool Goo::isLinked (Goo * goo) [inline]
Definition at line 97 of file goo.h.
References links.
Referenced by createLink(), BalloonGoo::destroyLink(), destroyLink(), DynamicGoo::moveToTarget(), and RopeJoint::paint().
bool Goo::isOnGround ()
Definition at line 48 of file goo.cpp.
References getPPosition(), groundPoint, and onGround.
Referenced by Level::giveTarget(), and DynamicGoo::moveToTarget().
void Goo::setSleep (bool status) [inline]
Definition at line 101 of file goo.h.
References sleeping.
Referenced by Introduction::setGoo(), and Introduction::setStartArea().
bool Goo::isSleeping () [inline]
Definition at line 104 of file goo.h.
References sleeping.
Referenced by Target::applyImpulse(), DynamicGoo::contactGround(), RemovableGoo::isDragable(), BalloonGoo::isDragable(), DynamicGoo::isDragable(), CollisionListener::PreSolve(), BalloonGoo::update(), and DynamicGoo::update().
bool Goo::createLink (Goo * goo) [virtual]
Reimplemented in BalloonGoo.
Definition at line 141 of file goo.cpp.
References body, following, isLinked(), links, maxJoints, nJoints(), sleeping, and stopFollow().
Referenced by Level::makeJoint().
bool Goo::destroyLink (Goo * goo) [virtual]
Reimplemented in BalloonGoo.
Definition at line 154 of file goo.cpp.
References body, hasJoint(), isDragging(), isLinked(), links, and loseLink().
Referenced by BalloonGoo::destroyLink(), Level::makeJoint(), and Joint::status().
virtual void Goo::contactGround () [pure virtual]
Implemented in DynamicGoo, and FixedGoo.
Referenced by CollisionListener::PostSolve().
virtual void Goo::contactGround (QPoint p) [pure virtual]
Implemented in DynamicGoo, and FixedGoo.
void Goo::destroyThis () [virtual]
Definition at line 183 of file goo.cpp.
References destroyGoo(), destroyJoint(), links, and loseLink().
Referenced by CollisionListener::PreSolve().
virtual QColor Goo::getColor () [pure virtual]
Implemented in DynamicGoo, and FixedGoo.
Referenced by Joint::paint(), and RopeJoint::paint().
void Goo::setTarget (Goo * goo)
Definition at line 197 of file goo.cpp.
References body, checkForConnection(), falling, following, isFalling(), loseLink(), prevTarget, removeGuest(), and target.
Referenced by Level::anchorToJoint(), Level::giveTarget(), and CollisionListener::PreSolve().
void Goo::move (QPoint p)
Definition at line 98 of file goo.cpp.
References body, isMoovable(), and toVec().
Referenced by Level::mousePressEvent(), and Level::timerEvent().
void Goo::jumpTo (QPoint p)
Definition at line 103 of file goo.cpp.
References SoundSystem::addSource(), body, SoundSystem::createSource(), dragable, falling, getPPosition(), moovable, SoundSystem::playSource(), radius, SoundSystem::setPitch(), SoundSystem::setPosition(), SoundSystem::setVolume(), sSystem, stopFollow(), and toVec().
Referenced by Target::applyImpulse().
virtual void Goo::catched () [inline, virtual]
Reimplemented in DynamicGoo.
Definition at line 122 of file goo.h.
virtual void Goo::lost () [inline, virtual]
Reimplemented in DynamicGoo.
Definition at line 123 of file goo.h.
b2Body* Goo::getBody () [inline]
Definition at line 126 of file goo.h.
References body.
Referenced by Target::applyForce(), Level::gooCatched(), RopeJoint::initialize(), Joint::initialize(), StickyLink::StickyLink(), and Level::timerEvent().
b2Vec2 Goo::getVPosition ()
Definition at line 127 of file goo.cpp.
References body.
Referenced by Target::applyForce(), Target::applyImpulse(), Level::giveTarget(), Joint::initialize(), Level::mousePressEvent(), DynamicGoo::moveToTarget(), CollisionListener::PostSolve(), StickyLink::StickyLink(), and Level::timerEvent().
b2Vec2 Goo::getVPositionScaled ()
Definition at line 131 of file goo.cpp.
References body.
QPoint Goo::getPPosition ()
Definition at line 136 of file goo.cpp.
References body, and toPoint().
Referenced by boundingRect(), DynamicGoo::contactGround(), Level::createJoints(), drag(), Level::getNearest(), isOnGround(), jumpTo(), Level::mouseMoveEvent(), Level::mouseReleaseEvent(), DynamicGoo::moveToTarget(), Level::overJoint(), Joint::paint(), RopeJoint::paint(), StickyLink::paint(), DynamicGoo::paint(), BalloonGoo::paintDebug(), DynamicGoo::paintDebug(), Level::paintEvent(), CollisionListener::PostSolve(), Joint::status(), Level::timerEvent(), BalloonGoo::update(), and DynamicGoo::update().
QList<Goo*> Goo::getLinks () [inline]
Definition at line 133 of file goo.h.
References links.
Referenced by Level::giveTarget().
Goo* Goo::getPrevious () [inline]
Definition at line 136 of file goo.h.
References prevTarget.
Referenced by Level::giveTarget(), and CollisionListener::PreSolve().
void Goo::moveToTarget () [inline, protected]
Reimplemented in DynamicGoo.
Definition at line 179 of file goo.h.
void Goo::stopFollow () [protected]
Definition at line 262 of file goo.cpp.
References checkForConnection(), following, prevTarget, removeGuest(), and target.
Referenced by checkForConnection(), BalloonGoo::createLink(), createLink(), BalloonGoo::drag(), drag(), drop(), fallDown(), jumpTo(), and DynamicGoo::moveToTarget().
void Goo::fallDown () [protected]
Definition at line 283 of file goo.cpp.
References body, falling, following, onGround, prevTarget, stopFollow(), and target.
Referenced by checkForConnection(), DynamicGoo::contactGround(), and DynamicGoo::moveToTarget().
void Goo::nextTargetPlease (Goo * previous) [signal]
Referenced by DynamicGoo::contactGround(), and DynamicGoo::moveToTarget().
void Goo::loseLink (Goo * goo) [signal]
Referenced by destroyLink(), destroyThis(), and setTarget().
void Goo::destroyGoo () [signal]
Referenced by destroyThis().
void Goo::destroyJoint (Goo * a, Goo * b) [signal]
Referenced by BalloonGoo::destroyLink(), and destroyThis().
void Goo::checkForNeighbors (QPoint p) [signal]
Referenced by BalloonGoo::update(), and DynamicGoo::update().
void Goo::stopDragging () [signal]
Referenced by DynamicGoo::contactGround().
void Goo::createSticky (QPoint p) [signal]
Referenced by DynamicGoo::contactGround().
void Goo::checkForConnection (Goo * goo) [private, slot]
Definition at line 274 of file goo.cpp.
References fallDown(), following, prevTarget, stopFollow(), and target.
Referenced by setTarget(), and stopFollow().
virtual void Goo::paint (QPainter & p) [pure virtual, slot]
Implemented in DynamicGoo, BalloonGoo, and FixedGoo.
Referenced by Level::paintEvent().
virtual void Goo::paintDebug (QPainter & p) [pure virtual, slot]
Implemented in DynamicGoo, BalloonGoo, and FixedGoo.
Referenced by Level::paintEvent().
virtual void Goo::neighborsFound () [inline, virtual, slot]
Reimplemented in DynamicGoo.
Definition at line 210 of file goo.h.
References sleeping.
Referenced by Level::checkForNeighbors().
virtual void Goo::update () [pure virtual, slot]
Implemented in DynamicGoo, BalloonGoo, and FixedGoo.
Referenced by Level::paintEvent().
Member Data Documentation
GooType Goo::type [protected]
Definition at line 141 of file goo.h.
Referenced by BalloonGoo::BalloonGoo(), DynamicGoo::DynamicGoo(), FixedGoo::FixedGoo(), getType(), Goo(), RemovableGoo::RemovableGoo(), and StickyGoo::StickyGoo().
QList<Goo*> Goo::links [protected]
Definition at line 142 of file goo.h.
Referenced by countingEnd(), BalloonGoo::createLink(), createLink(), BalloonGoo::destroyLink(), destroyLink(), destroyThis(), BalloonGoo::drag(), getLinks(), getNumberOf(), Goo(), hasJoint(), isLinked(), and nJoints().
int Goo::radius [protected]
Definition at line 143 of file goo.h.
Referenced by BalloonGoo::BalloonGoo(), boundingRect(), DynamicGoo::contactGround(), BalloonGoo::createLink(), BalloonGoo::destroyLink(), drag(), FixedGoo::FixedGoo(), getRadius(), Goo(), hasJoint(), jumpTo(), DynamicGoo::moveToTarget(), BalloonGoo::paint(), and DynamicGoo::paintDebug().
dragInfo Goo::info [protected]
Definition at line 144 of file goo.h.
Referenced by BalloonGoo::drag(), drag(), drop(), and Goo().
b2Body* Goo::body [protected]
Definition at line 145 of file goo.h.
Referenced by BalloonGoo::BalloonGoo(), DynamicGoo::contactGround(), BalloonGoo::createLink(), createLink(), BalloonGoo::destroyLink(), destroyLink(), BalloonGoo::drag(), drag(), drop(), DynamicGoo::DynamicGoo(), fallDown(), FixedGoo::FixedGoo(), getBody(), getPPosition(), getVPosition(), getVPositionScaled(), jumpTo(), move(), DynamicGoo::moveToTarget(), FixedGoo::paint(), BalloonGoo::paint(), DynamicGoo::paint(), FixedGoo::paintDebug(), BalloonGoo::paintDebug(), DynamicGoo::paintDebug(), setTarget(), BalloonGoo::update(), and DynamicGoo::update().
bool Goo::counted [protected]
Definition at line 148 of file goo.h.
Referenced by countingEnd(), getNumberOf(), and Goo().
bool Goo::dragable [protected]
Definition at line 152 of file goo.h.
Referenced by DynamicGoo::DynamicGoo(), Goo(), isDragable(), and jumpTo().
bool Goo::moovable [protected]
Definition at line 153 of file goo.h.
Referenced by DynamicGoo::DynamicGoo(), Goo(), isMoovable(), and jumpTo().
bool Goo::falling [protected]
Definition at line 154 of file goo.h.
Referenced by drop(), fallDown(), Goo(), isFalling(), jumpTo(), DynamicGoo::moveToTarget(), and setTarget().
bool Goo::following [protected]
Definition at line 155 of file goo.h.
Referenced by checkForConnection(), BalloonGoo::createLink(), createLink(), fallDown(), Goo(), DynamicGoo::moveToTarget(), setTarget(), and stopFollow().
bool Goo::dragging [protected]
Definition at line 156 of file goo.h.
Referenced by DynamicGoo::contactGround(), BalloonGoo::drag(), drag(), drop(), Goo(), isDragging(), and BalloonGoo::paint().
bool Goo::onGround [protected]
Definition at line 157 of file goo.h.
Referenced by DynamicGoo::contactGround(), BalloonGoo::drag(), drag(), fallDown(), FixedGoo::FixedGoo(), Goo(), isOnGround(), DynamicGoo::moveToTarget(), and DynamicGoo::paint().
bool Goo::selected [protected]
Definition at line 158 of file goo.h.
Referenced by Goo(), isSelected(), BalloonGoo::paint(), DynamicGoo::paint(), and select().
bool Goo::sleeping [protected]
Definition at line 160 of file goo.h.
Referenced by DynamicGoo::contactGround(), BalloonGoo::createLink(), createLink(), Goo(), isSleeping(), DynamicGoo::neighborsFound(), neighborsFound(), DynamicGoo::paint(), and setSleep().
QPoint Goo::groundPoint [protected]
Definition at line 163 of file goo.h.
Referenced by DynamicGoo::contactGround(), FixedGoo::FixedGoo(), Goo(), isOnGround(), and DynamicGoo::moveToTarget().
int Goo::minJoints [protected]
Definition at line 165 of file goo.h.
Referenced by Goo().
int Goo::maxJoints [protected]
Definition at line 165 of file goo.h.
Referenced by BalloonGoo::BalloonGoo(), canHaveJoint(), BalloonGoo::createLink(), createLink(), DynamicGoo::DynamicGoo(), FixedGoo::FixedGoo(), getMaxJoints(), and Goo().
int Goo::guestN [protected]
Definition at line 167 of file goo.h.
Referenced by BalloonGoo::BalloonGoo(), canHaveGuest(), getGuestNumber(), Goo(), newGuest(), and removeGuest().
int Goo::maxGuest [protected]
Definition at line 169 of file goo.h.
Referenced by BalloonGoo::BalloonGoo(), canHaveGuest(), Goo(), and newGuest().
int Goo::distanceToJoint [protected]
Definition at line 171 of file goo.h.
Referenced by BalloonGoo::BalloonGoo(), getDistanceToJoint(), Goo(), and DynamicGoo::moveToTarget().
double Goo::stickness [protected]
Definition at line 174 of file goo.h.
Referenced by getStickness(), Goo(), and StickyGoo::StickyGoo().
Goo* Goo::target [protected]
Definition at line 176 of file goo.h.
Referenced by checkForConnection(), DynamicGoo::contactGround(), fallDown(), getTarget(), Goo(), DynamicGoo::moveToTarget(), DynamicGoo::paintDebug(), setTarget(), and stopFollow().
Goo * Goo::prevTarget [protected]
Definition at line 176 of file goo.h.
Referenced by checkForConnection(), DynamicGoo::contactGround(), fallDown(), getPrevious(), Goo(), DynamicGoo::moveToTarget(), DynamicGoo::paintDebug(), setTarget(), and stopFollow().
QPair<unsigned int, unsigned int> Goo::scream [private]
Definition at line 184 of file goo.h.
Referenced by Goo().
The documentation for this class was generated from the following files:
goo.h
goo.cpp