OpenGOO: StickyLink Class Reference
StickyLink Class Reference
#include <stickylink.h>
Signals
void destroySticky ()
Public Member Functions
StickyLink (Goo *goo, b2Body *ground, QPoint contactPoint, b2World *world, double strength=4, QObject *parent=0)
void checkStatus ()
b2Joint * getJoint ()
void setJoint (b2Joint *j)
Goo * getGoo ()
void paint (QPainter &p)
Private Attributes
Goo * goo
b2DistanceJoint * joint
double strength
Detailed Description
Definition at line 13 of file stickylink.h.
Constructor & Destructor Documentation
StickyLink::StickyLink (Goo * goo, b2Body * ground, QPoint contactPoint, b2World * world, double strength = 4, QObject * parent = 0) [explicit]
Definition at line 7 of file stickylink.cpp.
References Goo::getBody(), Goo::getVPosition(), goo, joint, strength, and toVec().
Member Function Documentation
void StickyLink::checkStatus ()
Definition at line 21 of file stickylink.cpp.
References destroySticky(), goo, Goo::hasJoint(), Goo::isDragging(), joint, realStep, and strength.
b2Joint* StickyLink::getJoint () [inline]
Definition at line 22 of file stickylink.h.
References joint.
Referenced by Level::destroySticky().
void StickyLink::setJoint (b2Joint * j) [inline]
Definition at line 26 of file stickylink.h.
References joint.
Goo* StickyLink::getGoo () [inline]
Definition at line 30 of file stickylink.h.
References goo.
Referenced by Level::destroySticky().
void StickyLink::paint (QPainter & p)
Definition at line 32 of file stickylink.cpp.
References Goo::getPPosition(), goo, joint, and toPoint().
void StickyLink::destroySticky () [signal]
Referenced by checkStatus().
Member Data Documentation
Goo* StickyLink::goo [private]
Definition at line 39 of file stickylink.h.
Referenced by checkStatus(), getGoo(), paint(), and StickyLink().
b2DistanceJoint* StickyLink::joint [private]
Definition at line 41 of file stickylink.h.
Referenced by checkStatus(), getJoint(), paint(), setJoint(), and StickyLink().
double StickyLink::strength [private]
Definition at line 42 of file stickylink.h.
Referenced by checkStatus(), and StickyLink().
The documentation for this class was generated from the following files:
stickylink.h
stickylink.cpp