OpenGOO: RopeJoint Class Reference
RopeJoint Class Reference
#include <ropejoint.h>
Public Member Functions
RopeJoint (Goo *a, Goo *b, b2World *world, QObject *parent=0)
void status ()
~RopeJoint ()
Protected Member Functions
void initialize (b2World *world)
void paint (QPainter &p)
Private Attributes
QList< b2Joint * > joints
QList< b2Body * > bodies
b2World * world
Detailed Description
Definition at line 8 of file ropejoint.h.
Constructor & Destructor Documentation
RopeJoint::RopeJoint (Goo * a, Goo * b, b2World * world, QObject * parent = 0) [explicit]
Definition at line 8 of file ropejoint.cpp.
References initialize(), ROPE, Joint::type, and world.
RopeJoint::~RopeJoint ()
Definition at line 16 of file ropejoint.cpp.
References bodies, joints, and world.
Member Function Documentation
void RopeJoint::status () [virtual]
Reimplemented from Joint.
Definition at line 61 of file ropejoint.cpp.
void RopeJoint::initialize (b2World * world) [protected, virtual]
Reimplemented from Joint.
Definition at line 30 of file ropejoint.cpp.
References Joint::a, Joint::b, Goo::getBody(), and Joint::joint.
Referenced by RopeJoint().
void RopeJoint::paint (QPainter & p) [protected, virtual]
Reimplemented from Joint.
Definition at line 43 of file ropejoint.cpp.
References Joint::a, Joint::b, bodies, Joint::destroyJoint(), Goo::getColor(), Goo::getPPosition(), Goo::isLinked(), Joint::joint, and toPoint().
Member Data Documentation
QList<b2Joint*> RopeJoint::joints [private]
Definition at line 16 of file ropejoint.h.
Referenced by ~RopeJoint().
QList<b2Body*> RopeJoint::bodies [private]
Definition at line 17 of file ropejoint.h.
Referenced by paint(), and ~RopeJoint().
b2World* RopeJoint::world [private]
Definition at line 18 of file ropejoint.h.
Referenced by RopeJoint(), and ~RopeJoint().
The documentation for this class was generated from the following files:
ropejoint.h
ropejoint.cpp