OpenGOO: FixedGoo Class Reference
FixedGoo Class Reference
#include <fixedgoo.h>
Public Slots
void paint (QPainter &p)
void paintDebug (QPainter &p)
void update ()
Public Member Functions
FixedGoo (b2World *world, QPoint p=QPoint(0, 0), int radius=15, QObject *parent=0)
void contactGround ()
void contactGround (QPoint p)
QColor getColor ()
Detailed Description
Definition at line 6 of file fixedgoo.h.
Constructor & Destructor Documentation
FixedGoo::FixedGoo (b2World * world, QPoint p = QPoint(0,0), int radius = 15, QObject * parent = 0)
Definition at line 4 of file fixedgoo.cpp.
References Goo::body, FIXED_GOO, Goo::groundPoint, Goo::maxJoints, Goo::onGround, Goo::radius, toVec(), and Goo::type.
Member Function Documentation
void FixedGoo::contactGround () [virtual]
Implements Goo.
Definition at line 44 of file fixedgoo.cpp.
void FixedGoo::contactGround (QPoint p) [virtual]
Implements Goo.
Definition at line 47 of file fixedgoo.cpp.
QColor FixedGoo::getColor () [inline, virtual]
Implements Goo.
Definition at line 12 of file fixedgoo.h.
void FixedGoo::paint (QPainter & p) [virtual, slot]
Implements Goo.
Definition at line 25 of file fixedgoo.cpp.
References Goo::body, Goo::getRadius(), and toPoint().
void FixedGoo::paintDebug (QPainter & p) [virtual, slot]
Implements Goo.
Definition at line 31 of file fixedgoo.cpp.
References Goo::body, Goo::getRadius(), and toPoint().
void FixedGoo::update () [virtual, slot]
Implements Goo.
Definition at line 40 of file fixedgoo.cpp.
The documentation for this class was generated from the following files:
fixedgoo.h
fixedgoo.cpp