OpenGOO: SvgLevelLoader Class Reference
SvgLevelLoader Class Reference
#include <svglevelloader.h>
Signals
void fileError ()
void levelName (QString name)
void levelGoal (int goal)
void levelStartArea (int numberOfBalls, QRect area, int type)
void levelLimit (QRect limit)
void levelTarget (QPoint target)
void levelGround (QPoint center, QList< QPoint > groundPoints)
void levelGOO (QPoint center, int id, int type)
void levelJoint (Goo *a, Goo *b)
void levelGeometry (QSize size)
void addLevelThorn (QPoint center, QList< QPoint > thornPoints)
void addBackGroundShape (int id, QPolygon poly, QColor color)
Public Member Functions
SvgLevelLoader (QString path="", QObject *parent=0)
void setFile (QString path)
bool parse ()
void addGoo (int id, Goo *goo)
Private Member Functions
int getIndex (int id)
void parseBackground (QDomElement el)
QPoint parseTransform (QDomElement el)
QRect parseRect (QDomElement el, bool cal=false)
QPoint strToPoint (QString string)
QPoint parsePoint (QDomElement el)
QList< QPoint > parsePointList (QDomElement el)
QColor parseFill (QDomElement el)
Private Attributes
int h
int w
QPoint translation
QString path
QList< QPair< int, int > > links
QList< QPair< int, Goo * > > goos
Detailed Description
Definition at line 13 of file svglevelloader.h.
Constructor & Destructor Documentation
SvgLevelLoader::SvgLevelLoader (QString path = "", QObject * parent = 0) [inline, explicit]
Definition at line 17 of file svglevelloader.h.
Member Function Documentation
void SvgLevelLoader::setFile (QString path) [inline]
Definition at line 23 of file svglevelloader.h.
References path.
bool SvgLevelLoader::parse ()
Definition at line 21 of file svglevelloader.cpp.
References addLevelThorn(), fileError(), getIndex(), goos, h, levelGeometry(), levelGoal(), levelGOO(), levelGround(), levelJoint(), levelLimit(), levelName(), levelStartArea(), levelTarget(), links, parseBackground(), parsePoint(), parsePointList(), parseRect(), parseTransform(), path, translation, and w.
Referenced by Introduction::Introduction(), Level::restart(), and Level::startLevel().
void SvgLevelLoader::addGoo (int id, Goo * goo)
Definition at line 189 of file svglevelloader.cpp.
References goos.
Referenced by Level::setGoo().
int SvgLevelLoader::getIndex (int id) [private]
Definition at line 211 of file svglevelloader.cpp.
References goos.
Referenced by parse().
void SvgLevelLoader::parseBackground (QDomElement el) [private]
Definition at line 196 of file svglevelloader.cpp.
References addBackGroundShape(), parseFill(), parsePointList(), and toPoly().
Referenced by parse().
QPoint SvgLevelLoader::parseTransform (QDomElement el) [private]
Definition at line 218 of file svglevelloader.cpp.
References strToPoint().
Referenced by parse(), parsePoint(), parsePointList(), and parseRect().
QRect SvgLevelLoader::parseRect (QDomElement el, bool cal = false) [private]
Definition at line 234 of file svglevelloader.cpp.
References h, parseTransform(), and translation.
Referenced by parse().
QPoint SvgLevelLoader::strToPoint (QString string) [private]
Definition at line 266 of file svglevelloader.cpp.
Referenced by parsePointList(), and parseTransform().
QPoint SvgLevelLoader::parsePoint (QDomElement el) [private]
Definition at line 253 of file svglevelloader.cpp.
References parseTransform(), and translation.
Referenced by parse().
QList< QPoint > SvgLevelLoader::parsePointList (QDomElement el) [private]
Definition at line 281 of file svglevelloader.cpp.
References parseTransform(), strToPoint(), and translation.
Referenced by parse(), and parseBackground().
QColor SvgLevelLoader::parseFill (QDomElement el) [private]
Definition at line 333 of file svglevelloader.cpp.
Referenced by parseBackground().
void SvgLevelLoader::fileError () [signal]
Referenced by parse().
void SvgLevelLoader::levelName (QString name) [signal]
Referenced by parse().
void SvgLevelLoader::levelGoal (int goal) [signal]
Referenced by parse().
void SvgLevelLoader::levelStartArea (int numberOfBalls, QRect area, int type) [signal]
Referenced by parse().
void SvgLevelLoader::levelLimit (QRect limit) [signal]
Referenced by parse().
void SvgLevelLoader::levelTarget (QPoint target) [signal]
Referenced by parse().
void SvgLevelLoader::levelGround (QPoint center, QList< QPoint > groundPoints) [signal]
Referenced by parse().
void SvgLevelLoader::levelGOO (QPoint center, int id, int type) [signal]
Referenced by parse().
void SvgLevelLoader::levelJoint (Goo * a, Goo * b) [signal]
Referenced by parse().
void SvgLevelLoader::levelGeometry (QSize size) [signal]
Referenced by parse().
void SvgLevelLoader::addLevelThorn (QPoint center, QList< QPoint > thornPoints) [signal]
Referenced by parse().
void SvgLevelLoader::addBackGroundShape (int id, QPolygon poly, QColor color) [signal]
Referenced by parseBackground().
Member Data Documentation
int SvgLevelLoader::h [private]
Definition at line 33 of file svglevelloader.h.
Referenced by parse(), and parseRect().
int SvgLevelLoader::w [private]
Definition at line 33 of file svglevelloader.h.
Referenced by parse().
QPoint SvgLevelLoader::translation [private]
Definition at line 34 of file svglevelloader.h.
Referenced by parse(), parsePoint(), parsePointList(), and parseRect().
QString SvgLevelLoader::path [private]
Definition at line 62 of file svglevelloader.h.
Referenced by parse(), and setFile().
QList<QPair<int,int> > SvgLevelLoader::links [private]
Definition at line 65 of file svglevelloader.h.
Referenced by parse().
QList<QPair<int,Goo*> > SvgLevelLoader::goos [private]
Definition at line 67 of file svglevelloader.h.
Referenced by addGoo(), getIndex(), and parse().
The documentation for this class was generated from the following files:
svglevelloader.h
svglevelloader.cpp