OpenGOO: Level Class Reference
Level Class Reference
#include <level.h>
Signals
void closing ()
void eventBackToMainMenu ()
Public Member Functions
Level (QString level, BackGroundWidget *bg, QWidget *parent=0)
~Level ()
bool startLevel ()
Protected Member Functions
void timerEvent (QTimerEvent *)
void paintEvent (QPaintEvent *)
void keyReleaseEvent (QKeyEvent *)
void keyPressEvent (QKeyEvent *)
void mouseMoveEvent (QMouseEvent *)
void mousePressEvent (QMouseEvent *)
void mouseReleaseEvent (QMouseEvent *)
void wheelEvent (QWheelEvent *)
void resizeEvent (QResizeEvent *)
Private Slots
void setGoal (int goal)
void setName (QString name)
void setLimit (QRect limit)
void setTarget (QPoint target)
void setGround (QPoint gCenter, QList< QPoint > gList)
void setGoo (QPoint center, int id, int type=0)
void setStartArea (int n, QRect area, int type=0)
void setJoint (Goo *a, Goo *b)
void setLevelGeometry (QSize size)
void setThorns (QPoint center, QList< QPoint > list)
void createSticky (QPoint p)
void destroySticky ()
void checkForNeighbors (QPoint p)
void stopDragging ()
void addBGShape (int level, QPolygon poly, QColor color)
void destroyJoint (Joint *joint)
void destroyGOO ()
void gooCatched (Goo *goo)
void giveTarget (Goo *previous)
void destroyJoint (Goo *a, Goo *b)
void towerCatched ()
void towerLost ()
void resume ()
void restart ()
void closeAll ()
void backToMainMenu ()
Private Member Functions
void initialize ()
void clean ()
Joint * overJoint (Goo *goo)
Goo * getGooAt (QPoint p)
Goo * getNearest (QPoint p, QList< Goo * > l)
bool groundContains (Goo *goo)
bool groundContains (QPoint p, int radius)
void moveUp ()
void moveDown ()
void moveLeft ()
void moveRight ()
void moveOf (QPoint dP)
bool makeJoint (Goo *a, Goo *b)
QList< Goo * > possibleJoints (QPoint p)
bool createJoints (QPoint p)
void anchorToJoint (Goo *goo, Joint *j)
void paintScore (QPainter &p)
void paintWin (QPainter &p)
void paintTargetArrow (QPainter &p)
void paintButton (QPainter &p)
void clickButton (QPoint p)
bool zoom (float d)
void paintMute (QPainter &p)
void clickMute (QPoint p)
Private Attributes
float scale
SvgLevelLoader * loader
QPoint center
QPoint translation
bool onMenu
bool mooving
Menu * menu
b2World * world
float step
QList< Ground * > ground
QList< BackGround * > background
QList< Goo * > goos
QList< Goo * > goosToDestroy
QList< Joint * > joints
QList< Joint * > jointsToDestroy
QList< QPair< Goo *, QPoint > > stickyToCreate
QList< StickyLink * > stickys
QList< Object * > objects
Target * target
bool drag
Goo * dragged
Goo * selected
QPoint stopPosition
b2Vec2 mousePos
b2Vec2 mouseSpeed
QPoint absoluteMousePos
QString name
int goal
int points
bool catched
QRect limit
Direction dir
QList< Goo * > possibility
int showJointTimer
int positionTimer
int draggTimer
double time
QB2Draw * debugPainter
SoundSystem * soundSystem
PlaySoundThread * playSong
bool mute
BackGroundWidget * backGroundWidget
Detailed Description
Definition at line 48 of file level.h.
Constructor & Destructor Documentation
Level::Level (QString level, BackGroundWidget * bg, QWidget * parent = 0) [explicit]
Definition at line 35 of file level.cpp.
References addBGShape(), backToMainMenu(), catched, closeAll(), DEBUG, debugPainter, drag, dragged, eventBackToMainMenu(), flag, goal, initialize(), loader, menu, mooving, onMenu, points, restart(), resume(), scale, selected, setGoal(), setGoo(), setGround(), setJoint(), setLevelGeometry(), setLimit(), setName(), setStartArea(), setTarget(), setThorns(), showJointTimer, step, target, and world.
Level::~Level () [inline]
Definition at line 53 of file level.h.
References clean().
Member Function Documentation
bool Level::startLevel ()
Definition at line 112 of file level.cpp.
References DEBUG, flag, itime, loader, SvgLevelLoader::parse(), step, and time.
Referenced by MainWidget::levelSelected().
void Level::initialize () [private]
Definition at line 128 of file level.cpp.
References catched, center, DEBUG, debugPainter, dir, Direction::down, drag, dragged, flag, SoundSystem::initialize(), Direction::key, Direction::left, mute, playSong, points, Direction::right, selected, showJointTimer, soundSystem, sSystem, target, time, translation, Direction::up, and world.
Referenced by Level(), and restart().
void Level::clean () [private]
Definition at line 196 of file level.cpp.
References backGroundWidget, BackGroundWidget::clear(), DEBUG, debugPainter, flag, goos, ground, joints, objects, playSong, PlaySoundThread::quit(), soundSystem, stickys, and world.
Referenced by restart(), and ~Level().
Joint * Level::overJoint (Goo * goo) [private]
Definition at line 251 of file level.cpp.
References Goo::canHaveGuest(), Goo::getPPosition(), Goo::getRadius(), and joints.
Referenced by mouseReleaseEvent(), paintEvent(), and possibleJoints().
Goo * Level::getGooAt (QPoint p) [private]
Definition at line 262 of file level.cpp.
References goos, and scale.
Referenced by mouseMoveEvent(), and mousePressEvent().
Goo * Level::getNearest (QPoint p, QList< Goo * > l) [private]
Definition at line 515 of file level.cpp.
References Goo::getPPosition().
Referenced by createJoints(), and paintEvent().
bool Level::groundContains (Goo * goo) [private]
Definition at line 533 of file level.cpp.
References ground.
Referenced by timerEvent().
bool Level::groundContains (QPoint p, int radius) [private]
Definition at line 539 of file level.cpp.
References ground.
void Level::moveUp () [private]
Definition at line 275 of file level.cpp.
References backGroundWidget, limit, positionTimer, scale, BackGroundWidget::translated(), and translation.
Referenced by timerEvent().
void Level::moveDown () [private]
Definition at line 285 of file level.cpp.
References backGroundWidget, limit, positionTimer, scale, BackGroundWidget::translated(), and translation.
Referenced by timerEvent().
void Level::moveLeft () [private]
Definition at line 301 of file level.cpp.
References backGroundWidget, limit, positionTimer, scale, BackGroundWidget::translated(), and translation.
Referenced by timerEvent().
void Level::moveRight () [private]
Definition at line 293 of file level.cpp.
References backGroundWidget, limit, positionTimer, scale, BackGroundWidget::translated(), and translation.
Referenced by timerEvent().
void Level::moveOf (QPoint dP) [private]
Definition at line 310 of file level.cpp.
References backGroundWidget, DEBUG, flag, limit, scale, BackGroundWidget::translated(), and translation.
Referenced by mouseMoveEvent(), and zoom().
bool Level::makeJoint (Goo * a, Goo * b) [private]
Definition at line 328 of file level.cpp.
References BALOON, Goo::createLink(), destroyJoint(), Goo::destroyLink(), Goo::getType(), joints, and world.
Referenced by createJoints(), and setJoint().
QList< Goo * > Level::possibleJoints (QPoint p) [private]
Definition at line 350 of file level.cpp.
References dragged, Goo::getDistanceToJoint(), Goo::getRadius(), goos, overJoint(), and toVec().
Referenced by createJoints(), mouseMoveEvent(), and timerEvent().
bool Level::createJoints (QPoint p) [private]
Definition at line 370 of file level.cpp.
References BALOON, dragged, getNearest(), Goo::getPPosition(), Goo::getType(), Goo::hasJoint(), makeJoint(), and possibleJoints().
Referenced by mouseReleaseEvent().
void Level::anchorToJoint (Goo * goo, Joint * j) [private]
Definition at line 394 of file level.cpp.
References Goo::canHaveGuest(), Joint::goo(), and Goo::setTarget().
Referenced by mouseReleaseEvent(), and paintEvent().
void Level::paintScore (QPainter & p) [private]
Definition at line 1025 of file level.cpp.
References flag, FPS, fps, goal, points, time, and time2string().
Referenced by paintEvent().
void Level::paintWin (QPainter & p) [private]
Definition at line 1056 of file level.cpp.
References goal, name, onMenu, and points.
Referenced by paintEvent().
void Level::paintTargetArrow (QPainter & p) [private]
Definition at line 1077 of file level.cpp.
References center, Target::getVPosition(), scale, target, toPoint(), and translation.
Referenced by paintEvent().
void Level::paintButton (QPainter & p) [private]
Definition at line 1115 of file level.cpp.
References onMenu.
Referenced by paintEvent().
void Level::clickButton (QPoint p) [private]
Definition at line 1124 of file level.cpp.
References onMenu.
Referenced by mouseReleaseEvent().
bool Level::zoom (float d) [private]
Definition at line 1173 of file level.cpp.
References limit, mousePos, moveOf(), and scale.
Referenced by wheelEvent().
void Level::paintMute (QPainter & p) [private]
Definition at line 1130 of file level.cpp.
References mute, onMenu, and target.
Referenced by paintEvent().
void Level::clickMute (QPoint p) [private]
Definition at line 1149 of file level.cpp.
References mute, onMenu, PlaySoundThread::pauseSong(), playSong, and PlaySoundThread::startSong().
Referenced by mouseReleaseEvent().
void Level::timerEvent (QTimerEvent * e) [protected]
Definition at line 402 of file level.cpp.
References Target::applyForces(), Target::checkTower(), destroySticky(), dir, Direction::down, Goo::drag(), drag, dragged, draggTimer, fps, Goo::getBody(), Goo::getPPosition(), Goo::getVPosition(), goal, goos, goosToDestroy, ground, groundContains(), itime, joints, jointsToDestroy, Direction::left, mousePos, Goo::move(), moveDown(), moveLeft(), moveRight(), moveUp(), onMenu, points, positionTimer, possibility, possibleJoints(), realStep, Direction::right, scale, showJointTimer, step, stickys, stickyToCreate, target, time, toPoint(), toVec(), translation, Direction::up, and world.
void Level::paintEvent (QPaintEvent * e) [protected]
Definition at line 545 of file level.cpp.
References anchorToJoint(), BALOON, center, DEBUG, debugPainter, DELAY, drag, dragged, flag, getNearest(), Goo::getPPosition(), Goo::getType(), goos, joints, menu, objects, ONLYTEXT, onMenu, OPENGL, overJoint(), Menu::paint(), Goo::paint(), paintButton(), Goo::paintDebug(), paintMute(), paintScore(), paintTargetArrow(), paintWin(), possibility, scale, selected, QB2Draw::setPainter(), showJointTimer, stickys, translation, Goo::update(), and world.
void Level::keyReleaseEvent (QKeyEvent * e) [protected]
Definition at line 703 of file level.cpp.
References dir, Direction::down, Direction::key, Direction::left, mute, onMenu, PlaySoundThread::pauseSong(), playSong, Direction::right, PlaySoundThread::startSong(), and Direction::up.
void Level::keyPressEvent (QKeyEvent * e) [protected]
Definition at line 736 of file level.cpp.
References dir, Direction::down, Direction::key, Direction::left, positionTimer, Direction::right, and Direction::up.
void Level::mouseMoveEvent (QMouseEvent * e) [protected]
Definition at line 762 of file level.cpp.
References dir, Direction::down, drag, dragged, getGooAt(), Goo::getPPosition(), goal, Direction::key, Direction::left, mooving, mousePos, mouseSpeed, moveOf(), onMenu, points, positionTimer, possibility, possibleJoints(), Direction::right, scale, Goo::select(), selected, showJointTimer, toPoint(), toVec(), translation, and Direction::up.
void Level::mousePressEvent (QMouseEvent * e) [protected]
Definition at line 834 of file level.cpp.
References center, Goo::drag(), drag, dragged, draggTimer, getGooAt(), Goo::getVPosition(), goal, mooving, mousePos, mouseSpeed, Goo::move(), onMenu, points, possibility, scale, Goo::select(), selected, toVec(), and translation.
void Level::mouseReleaseEvent (QMouseEvent * e) [protected]
Definition at line 890 of file level.cpp.
References anchorToJoint(), clickButton(), clickMute(), createJoints(), DELAY, drag, dragged, Goo::drop(), Goo::getPPosition(), Goo::hasJoint(), menu, mooving, Menu::mouseRelease(), mouseSpeed, mute, onMenu, overJoint(), PlaySoundThread::pauseSong(), playSong, possibility, showJointTimer, toVec(), and translation.
void Level::wheelEvent (QWheelEvent * e) [protected]
Definition at line 921 of file level.cpp.
References backGroundWidget, dragged, mousePos, scale, BackGroundWidget::setScale(), toVec(), and zoom().
void Level::resizeEvent (QResizeEvent * e) [protected]
Definition at line 940 of file level.cpp.
References menu, and Menu::setGeometry().
void Level::closing () [signal]
Referenced by closeAll().
void Level::eventBackToMainMenu () [signal]
Referenced by backToMainMenu(), and Level().
void Level::setGoal (int goal) [private, slot]
Definition at line 1229 of file level.cpp.
References DEBUG, flag, and goal.
Referenced by Level().
void Level::setName (QString name) [inline, private, slot]
Definition at line 204 of file level.h.
References name.
Referenced by Level().
void Level::setLimit (QRect limit) [private, slot]
Definition at line 1234 of file level.cpp.
References backGroundWidget, DEBUG, flag, limit, scale, BackGroundWidget::setLimit(), BackGroundWidget::setScale(), BackGroundWidget::translated(), and translation.
Referenced by Level().
void Level::setTarget (QPoint target) [private, slot]
Definition at line 1257 of file level.cpp.
References backGroundWidget, DEBUG, flag, gooCatched(), limit, BackGroundWidget::setTarget(), target, towerCatched(), towerLost(), and world.
Referenced by Level().
void Level::setGround (QPoint gCenter, QList< QPoint > gList) [private, slot]
Definition at line 1250 of file level.cpp.
References BackGroundWidget::addGround(), backGroundWidget, DEBUG, flag, ground, and world.
Referenced by Level().
void Level::setGoo (QPoint center, int id, int type = 0) [private, slot]
Definition at line 1335 of file level.cpp.
References SvgLevelLoader::addGoo(), checkForNeighbors(), createSticky(), destroyGOO(), destroyJoint(), giveTarget(), goos, INTERVALL, loader, RADIUS, stopDragging(), and world.
Referenced by Level().
void Level::setStartArea (int n, QRect area, int type = 0) [private, slot]
Definition at line 1269 of file level.cpp.
References checkForNeighbors(), createSticky(), DEBUG, destroyGOO(), destroyJoint(), flag, giveTarget(), goos, INTERVALL, RADIUS, and world.
Referenced by Level().
void Level::setJoint (Goo * a, Goo * b) [private, slot]
Definition at line 1327 of file level.cpp.
References DEBUG, flag, and makeJoint().
Referenced by Level().
void Level::setLevelGeometry (QSize size) [private, slot]
Definition at line 1393 of file level.cpp.
References DEBUG, and flag.
Referenced by Level().
void Level::setThorns (QPoint center, QList< QPoint > list) [private, slot]
Definition at line 1397 of file level.cpp.
References objects, and world.
Referenced by Level().
void Level::createSticky (QPoint p) [private, slot]
Definition at line 1402 of file level.cpp.
References stickyToCreate.
Referenced by setGoo(), and setStartArea().
void Level::destroySticky () [private, slot]
Definition at line 1412 of file level.cpp.
References StickyLink::getGoo(), StickyLink::getJoint(), stickys, DynamicGoo::unstick(), and world.
Referenced by timerEvent().
void Level::checkForNeighbors (QPoint p) [private, slot]
Definition at line 1431 of file level.cpp.
References goos, Goo::neighborsFound(), and toVec().
Referenced by setGoo(), and setStartArea().
void Level::stopDragging () [private, slot]
Definition at line 1458 of file level.cpp.
References drag, dragged, mooving, and possibility.
Referenced by setGoo().
void Level::addBGShape (int level, QPolygon poly, QColor color) [private, slot]
Definition at line 1475 of file level.cpp.
References BackGroundWidget::addBackGround(), BackGround::addPolygon(), background, backGroundWidget, and BackGround::setDelta().
Referenced by Level().
void Level::destroyJoint (Joint * joint) [private, slot]
Definition at line 945 of file level.cpp.
References jointsToDestroy.
Referenced by makeJoint(), setGoo(), and setStartArea().
void Level::destroyGOO () [private, slot]
Definition at line 1208 of file level.cpp.
References drag, dragged, and goosToDestroy.
Referenced by setGoo(), and setStartArea().
void Level::gooCatched (Goo * goo) [private, slot]
Definition at line 1006 of file level.cpp.
References Goo::getBody(), goos, points, and world.
Referenced by restart(), and setTarget().
void Level::giveTarget (Goo * previous) [private, slot]
Definition at line 950 of file level.cpp.
References catched, Goo::getLinks(), Goo::getPrevious(), Goo::getVPosition(), goos, Goo::isOnGround(), Goo::setTarget(), and target.
Referenced by setGoo(), and setStartArea().
void Level::destroyJoint (Goo * a, Goo * b) [private, slot]
Definition at line 1219 of file level.cpp.
References joints, and jointsToDestroy.
void Level::towerCatched () [private, slot]
Definition at line 1012 of file level.cpp.
References catched, and goos.
Referenced by restart(), and setTarget().
void Level::towerLost () [private, slot]
Definition at line 1018 of file level.cpp.
References catched, and goos.
Referenced by restart(), and setTarget().
void Level::resume () [inline, private, slot]
Definition at line 240 of file level.h.
References onMenu, playSong, and PlaySoundThread::startSong().
Referenced by Level(), and restart().
void Level::restart () [private, slot]
Definition at line 1198 of file level.cpp.
References clean(), gooCatched(), initialize(), loader, SvgLevelLoader::parse(), resume(), target, towerCatched(), and towerLost().
Referenced by Level().
void Level::closeAll () [inline, private, slot]
Definition at line 245 of file level.h.
References closing().
Referenced by Level().
void Level::backToMainMenu () [inline, private, slot]
Definition at line 248 of file level.h.
References eventBackToMainMenu().
Referenced by Level().
Member Data Documentation
float Level::scale [private]
Definition at line 61 of file level.h.
Referenced by getGooAt(), Level(), mouseMoveEvent(), mousePressEvent(), moveDown(), moveLeft(), moveOf(), moveRight(), moveUp(), paintEvent(), paintTargetArrow(), setLimit(), timerEvent(), wheelEvent(), and zoom().
SvgLevelLoader* Level::loader [private]
Definition at line 63 of file level.h.
Referenced by Level(), restart(), setGoo(), and startLevel().
QPoint Level::center [private]
Definition at line 66 of file level.h.
Referenced by initialize(), mousePressEvent(), paintEvent(), and paintTargetArrow().
QPoint Level::translation [private]
Definition at line 67 of file level.h.
Referenced by initialize(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), moveDown(), moveLeft(), moveOf(), moveRight(), moveUp(), paintEvent(), paintTargetArrow(), setLimit(), and timerEvent().
bool Level::onMenu [private]
Definition at line 68 of file level.h.
Referenced by clickButton(), clickMute(), keyReleaseEvent(), Level(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paintButton(), paintEvent(), paintMute(), paintWin(), resume(), and timerEvent().
bool Level::mooving [private]
Definition at line 69 of file level.h.
Referenced by Level(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and stopDragging().
Menu* Level::menu [private]
Definition at line 70 of file level.h.
Referenced by Level(), mouseReleaseEvent(), paintEvent(), and resizeEvent().
b2World* Level::world [private]
Definition at line 72 of file level.h.
Referenced by clean(), destroySticky(), gooCatched(), initialize(), Level(), makeJoint(), paintEvent(), setGoo(), setGround(), setStartArea(), setTarget(), setThorns(), and timerEvent().
float Level::step [private]
Definition at line 73 of file level.h.
Referenced by Level(), startLevel(), and timerEvent().
QList<Ground *> Level::ground [private]
Definition at line 75 of file level.h.
Referenced by clean(), groundContains(), setGround(), and timerEvent().
QList<BackGround*> Level::background [private]
Definition at line 76 of file level.h.
Referenced by addBGShape().
QList<Goo*> Level::goos [private]
Definition at line 78 of file level.h.
Referenced by checkForNeighbors(), clean(), getGooAt(), giveTarget(), gooCatched(), paintEvent(), possibleJoints(), setGoo(), setStartArea(), timerEvent(), towerCatched(), and towerLost().
QList<Goo*> Level::goosToDestroy [private]
Definition at line 79 of file level.h.
Referenced by destroyGOO(), and timerEvent().
QList<Joint*> Level::joints [private]
Definition at line 82 of file level.h.
Referenced by clean(), destroyJoint(), makeJoint(), overJoint(), paintEvent(), and timerEvent().
QList<Joint*> Level::jointsToDestroy [private]
Definition at line 83 of file level.h.
Referenced by destroyJoint(), and timerEvent().
QList< QPair<Goo*,QPoint> > Level::stickyToCreate [private]
Definition at line 87 of file level.h.
Referenced by createSticky(), and timerEvent().
QList<StickyLink*> Level::stickys [private]
Definition at line 89 of file level.h.
Referenced by clean(), destroySticky(), paintEvent(), and timerEvent().
QList<Object*> Level::objects [private]
Definition at line 91 of file level.h.
Referenced by clean(), paintEvent(), and setThorns().
Target* Level::target [private]
Definition at line 92 of file level.h.
Referenced by giveTarget(), initialize(), Level(), paintMute(), paintTargetArrow(), restart(), setTarget(), and timerEvent().
bool Level::drag [private]
Definition at line 93 of file level.h.
Referenced by destroyGOO(), initialize(), Level(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paintEvent(), stopDragging(), and timerEvent().
Goo* Level::dragged [private]
Definition at line 94 of file level.h.
Referenced by createJoints(), destroyGOO(), initialize(), Level(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paintEvent(), possibleJoints(), stopDragging(), timerEvent(), and wheelEvent().
Goo* Level::selected [private]
Definition at line 95 of file level.h.
Referenced by initialize(), Level(), mouseMoveEvent(), mousePressEvent(), and paintEvent().
QPoint Level::stopPosition [private]
Definition at line 96 of file level.h.
b2Vec2 Level::mousePos [private]
Definition at line 98 of file level.h.
Referenced by mouseMoveEvent(), mousePressEvent(), timerEvent(), wheelEvent(), and zoom().
b2Vec2 Level::mouseSpeed [private]
Definition at line 99 of file level.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
QPoint Level::absoluteMousePos [private]
Definition at line 100 of file level.h.
QString Level::name [private]
Definition at line 102 of file level.h.
Referenced by paintWin(), and setName().
int Level::goal [private]
Definition at line 103 of file level.h.
Referenced by Level(), mouseMoveEvent(), mousePressEvent(), paintScore(), paintWin(), setGoal(), and timerEvent().
int Level::points [private]
Definition at line 104 of file level.h.
Referenced by gooCatched(), initialize(), Level(), mouseMoveEvent(), mousePressEvent(), paintScore(), paintWin(), and timerEvent().
bool Level::catched [private]
Definition at line 105 of file level.h.
Referenced by giveTarget(), initialize(), Level(), towerCatched(), and towerLost().
QRect Level::limit [private]
Definition at line 106 of file level.h.
Referenced by moveDown(), moveLeft(), moveOf(), moveRight(), moveUp(), setLimit(), setTarget(), and zoom().
Direction Level::dir [private]
Definition at line 107 of file level.h.
Referenced by initialize(), keyPressEvent(), keyReleaseEvent(), mouseMoveEvent(), and timerEvent().
QList<Goo*> Level::possibility [private]
Definition at line 108 of file level.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paintEvent(), stopDragging(), and timerEvent().
int Level::showJointTimer [private]
Definition at line 111 of file level.h.
Referenced by initialize(), Level(), mouseMoveEvent(), mouseReleaseEvent(), paintEvent(), and timerEvent().
int Level::positionTimer [private]
Definition at line 113 of file level.h.
Referenced by keyPressEvent(), mouseMoveEvent(), moveDown(), moveLeft(), moveRight(), moveUp(), and timerEvent().
int Level::draggTimer [private]
Definition at line 114 of file level.h.
Referenced by mousePressEvent(), and timerEvent().
double Level::time [private]
Definition at line 117 of file level.h.
Referenced by initialize(), paintScore(), startLevel(), and timerEvent().
QB2Draw* Level::debugPainter [private]
Definition at line 120 of file level.h.
Referenced by clean(), initialize(), Level(), and paintEvent().
SoundSystem* Level::soundSystem [private]
Definition at line 123 of file level.h.
Referenced by clean(), and initialize().
PlaySoundThread* Level::playSong [private]
Definition at line 124 of file level.h.
Referenced by clean(), clickMute(), initialize(), keyReleaseEvent(), mouseReleaseEvent(), and resume().
bool Level::mute [private]
Definition at line 126 of file level.h.
Referenced by clickMute(), initialize(), keyReleaseEvent(), mouseReleaseEvent(), and paintMute().
BackGroundWidget* Level::backGroundWidget [private]
Definition at line 129 of file level.h.
Referenced by addBGShape(), clean(), moveDown(), moveLeft(), moveOf(), moveRight(), moveUp(), setGround(), setLimit(), setTarget(), and wheelEvent().
The documentation for this class was generated from the following files:
level.h
level.cpp