OpenGOO: Menu Class Reference
Menu Class Reference
The class 'menu' draws the game menu reading the entries in menu.index file located in 'resources' folder.
#include <menu.h>
Public Slots
void paint (QPainter &p)
Signals
void eventClose ()
void eventResume ()
void eventRestart ()
void eventBackToMainMenu ()
Public Member Functions
Menu (QRect geometry, QObject *parent=0)
void mouseRelease (QMouseEvent *e)
void setGeometry (QRect geometry)
Private Member Functions
void loadMenuFile ()
void computeHeight ()
void paintButton (int ind, QPainter &p)
Private Attributes
QStringList index
QList< QRect > buttons
QGraphicsScene * scene
QRect geometry
int selected
int height
Detailed Description
The class 'menu' draws the game menu reading the entries in menu.index file located in 'resources' folder.
Definition at line 18 of file menu.h.
Constructor & Destructor Documentation
Menu::Menu (QRect geometry, QObject * parent = 0) [explicit]
Definition at line 11 of file menu.cpp.
References computeHeight(), geometry, loadMenuFile(), and selected.
Member Function Documentation
void Menu::mouseRelease (QMouseEvent * e)
Definition at line 85 of file menu.cpp.
References buttons, eventBackToMainMenu(), eventClose(), eventRestart(), eventResume(), and index.
Referenced by Level::mouseReleaseEvent().
void Menu::setGeometry (QRect geometry)
Definition at line 115 of file menu.cpp.
References buttons, geometry, and height.
Referenced by Level::resizeEvent().
void Menu::loadMenuFile () [private]
Definition at line 34 of file menu.cpp.
References buttons, geometry, height, and index.
Referenced by Menu().
void Menu::computeHeight () [private]
Definition at line 78 of file menu.cpp.
References height.
Referenced by Menu().
void Menu::paintButton (int ind, QPainter & p) [private]
Definition at line 62 of file menu.cpp.
References buttons, and index.
Referenced by paint().
void Menu::eventClose () [signal]
Referenced by mouseRelease().
void Menu::eventResume () [signal]
Referenced by mouseRelease().
void Menu::eventRestart () [signal]
Referenced by mouseRelease().
void Menu::eventBackToMainMenu () [signal]
Referenced by mouseRelease().
void Menu::paint (QPainter & p) [slot]
Definition at line 22 of file menu.cpp.
References DEBUG, flag, geometry, index, and paintButton().
Referenced by Level::paintEvent().
Member Data Documentation
QStringList Menu::index [private]
Definition at line 26 of file menu.h.
Referenced by loadMenuFile(), mouseRelease(), paint(), and paintButton().
QList<QRect> Menu::buttons [private]
Definition at line 27 of file menu.h.
Referenced by loadMenuFile(), mouseRelease(), paintButton(), and setGeometry().
QGraphicsScene* Menu::scene [private]
Definition at line 28 of file menu.h.
QRect Menu::geometry [private]
Definition at line 29 of file menu.h.
Referenced by loadMenuFile(), Menu(), paint(), and setGeometry().
int Menu::selected [private]
Definition at line 30 of file menu.h.
Referenced by Menu().
int Menu::height [private]
Definition at line 31 of file menu.h.
Referenced by computeHeight(), loadMenuFile(), and setGeometry().
The documentation for this class was generated from the following files:
menu.h
menu.cpp