OpenGOO: QB2Draw Class Reference
QB2Draw Class Reference
#include <qb2draw.h>
Public Slots
void updateGeometry (QRect displayGeometry)
void setPainter (QPainter *p)
Public Member Functions
QB2Draw (QRect displayGeometry, QPainter *p=NULL)
void DrawPolygon (const b2Vec2 *vertices, int32 vertexCount, const b2Color &color)
void DrawSolidPolygon (const b2Vec2 *vertices, int32 vertexCount, const b2Color &color)
void DrawCircle (const b2Vec2 &center, float32 radius, const b2Color &color)
void DrawSolidCircle (const b2Vec2 &center, float32 radius, const b2Vec2 &axis, const b2Color &color)
void DrawSegment (const b2Vec2 &p1, const b2Vec2 &p2, const b2Color &color)
void DrawTransform (const b2Transform &xf)
Private Member Functions
QPoint toQPoint (b2Vec2 vec)
QColor toQColor (b2Color color)
Private Attributes
QPainter * painter
QRect geometry
float scale
Detailed Description
Definition at line 7 of file qb2draw.h.
Constructor & Destructor Documentation
QB2Draw::QB2Draw (QRect displayGeometry, QPainter * p = NULL) [inline]
Definition at line 11 of file qb2draw.h.
Member Function Documentation
void QB2Draw::DrawPolygon (const b2Vec2 * vertices, int32 vertexCount, const b2Color & color)
Definition at line 14 of file qb2draw.cpp.
References painter, and toQPoint().
void QB2Draw::DrawSolidPolygon (const b2Vec2 * vertices, int32 vertexCount, const b2Color & color)
Definition at line 29 of file qb2draw.cpp.
References painter, and toQPoint().
void QB2Draw::DrawCircle (const b2Vec2 & center, float32 radius, const b2Color & color)
Definition at line 41 of file qb2draw.cpp.
References painter, scale, toQColor(), and toQPoint().
void QB2Draw::DrawSolidCircle (const b2Vec2 & center, float32 radius, const b2Vec2 & axis, const b2Color & color)
Definition at line 50 of file qb2draw.cpp.
References painter, scale, and toQPoint().
void QB2Draw::DrawSegment (const b2Vec2 & p1, const b2Vec2 & p2, const b2Color & color)
Definition at line 73 of file qb2draw.cpp.
References painter, and toQPoint().
void QB2Draw::DrawTransform (const b2Transform & xf)
Definition at line 86 of file qb2draw.cpp.
References painter, and toQPoint().
QPoint QB2Draw::toQPoint (b2Vec2 vec) [inline, private]
Definition at line 30 of file qb2draw.h.
References scale.
Referenced by DrawCircle(), DrawPolygon(), DrawSegment(), DrawSolidCircle(), DrawSolidPolygon(), and DrawTransform().
QColor QB2Draw::toQColor (b2Color color) [inline, private]
Definition at line 33 of file qb2draw.h.
Referenced by DrawCircle().
void QB2Draw::updateGeometry (QRect displayGeometry) [inline, slot]
Definition at line 38 of file qb2draw.h.
References geometry.
void QB2Draw::setPainter (QPainter * p) [inline, slot]
Definition at line 41 of file qb2draw.h.
References painter.
Referenced by Level::paintEvent().
Member Data Documentation
QPainter* QB2Draw::painter [private]
Definition at line 26 of file qb2draw.h.
Referenced by DrawCircle(), DrawPolygon(), DrawSegment(), DrawSolidCircle(), DrawSolidPolygon(), DrawTransform(), and setPainter().
QRect QB2Draw::geometry [private]
Definition at line 27 of file qb2draw.h.
Referenced by updateGeometry().
float QB2Draw::scale [private]
Definition at line 28 of file qb2draw.h.
Referenced by DrawCircle(), DrawSolidCircle(), and toQPoint().
The documentation for this class was generated from the following files:
qb2draw.h
qb2draw.cpp