OpenGOO: MainWidget Class Reference
MainWidget Class Reference
The MainWidget class is the starting point of the game.
#include <mainwidget.h>
Public Member Functions
MainWidget (QRect geometry, QWidget *parent=0)
~MainWidget ()
Protected Member Functions
void closeEvent (QCloseEvent *)
Private Slots
void levelSelected ()
void backToMainMenu ()
void startSelection ()
Private Attributes
Level * level
LevelSelector * levelS
BackGroundWidget * bgWidget
QGridLayout * layout
Introduction * intro
Detailed Description
The MainWidget class is the starting point of the game.
Definition at line 16 of file mainwidget.h.
Constructor & Destructor Documentation
MainWidget::MainWidget (QRect geometry, QWidget * parent = 0)
Definition at line 8 of file mainwidget.cpp.
References intro, layout, level, levelS, and startSelection().
MainWidget::~MainWidget ()
Definition at line 27 of file mainwidget.cpp.
References level, and levelS.
Member Function Documentation
void MainWidget::closeEvent (QCloseEvent * e) [protected]
Definition at line 33 of file mainwidget.cpp.
References level.
void MainWidget::levelSelected () [private, slot]
Definition at line 42 of file mainwidget.cpp.
References backToMainMenu(), bgWidget, DEBUG, flag, LevelSelector::getLevelSelected(), layout, level, levelS, and Level::startLevel().
Referenced by backToMainMenu(), and startSelection().
void MainWidget::backToMainMenu () [private, slot]
Definition at line 80 of file mainwidget.cpp.
References bgWidget, DEBUG, flag, layout, level, levelS, and levelSelected().
Referenced by levelSelected().
void MainWidget::startSelection () [private, slot]
Definition at line 96 of file mainwidget.cpp.
References intro, layout, levelS, and levelSelected().
Referenced by MainWidget().
Member Data Documentation
Level* MainWidget::level [private]
Definition at line 25 of file mainwidget.h.
Referenced by backToMainMenu(), closeEvent(), levelSelected(), MainWidget(), and ~MainWidget().
LevelSelector* MainWidget::levelS [private]
Definition at line 26 of file mainwidget.h.
Referenced by backToMainMenu(), levelSelected(), MainWidget(), startSelection(), and ~MainWidget().
BackGroundWidget* MainWidget::bgWidget [private]
Definition at line 27 of file mainwidget.h.
Referenced by backToMainMenu(), and levelSelected().
QGridLayout* MainWidget::layout [private]
Definition at line 28 of file mainwidget.h.
Referenced by backToMainMenu(), levelSelected(), MainWidget(), and startSelection().
Introduction* MainWidget::intro [private]
Definition at line 29 of file mainwidget.h.
Referenced by MainWidget(), and startSelection().
The documentation for this class was generated from the following files:
mainwidget.h
mainwidget.cpp