OpenGOO: tools.cpp File Reference
tools.cpp File Reference
#include "tools.h"
#include <QPolygon>
#include <QString>
Functions
QPolygon toPoly (const QList< QPoint > &ps, QPoint center)
Convert a QList of QPoint in a QPolygon transated of *center*.
QString time2string (int time)
Function Documentation
QPolygon toPoly (const QList< QPoint > & ps, QPoint center)
Convert a QList of QPoint in a QPolygon transated of *center*.
Definition at line 10 of file tools.cpp.
Referenced by Ground::Ground(), SvgLevelLoader::parseBackground(), and Thorn::Thorn().
QString time2string (int time)
Definition at line 18 of file tools.cpp.
Referenced by Level::paintScore().