OpenGOO: tools.h File Reference
tools.h File Reference
#include <Box2D/Box2D.h>
#include <QList>
#include <QPoint>
Functions
b2Vec2 toVec (QPoint p)
Convert a QPoint in a b2Vec2.
QPoint toPoint (b2Vec2 v)
Convert a b2Vec2 in a QPoint.
QPolygon toPoly (const QList< QPoint > &ps, QPoint center)
Convert a QList of QPoint in a QPolygon transated of *center*.
QString time2string (int time)
Function Documentation
b2Vec2 toVec (QPoint p) [inline]
Convert a QPoint in a b2Vec2.
Definition at line 15 of file tools.h.
Referenced by Target::applyForce(), Target::applyImpulse(), Level::checkForNeighbors(), Target::checkTower(), DynamicGoo::DynamicGoo(), FixedGoo::FixedGoo(), Target::getVPosition(), Ground::Ground(), Goo::jumpTo(), Ground::makeShape(), Level::mouseMoveEvent(), Level::mousePressEvent(), Level::mouseReleaseEvent(), Goo::move(), DynamicGoo::moveToTarget(), Level::possibleJoints(), StickyLink::StickyLink(), Target::Target(), Thorn::Thorn(), Level::timerEvent(), and Level::wheelEvent().
QPoint toPoint (b2Vec2 v) [inline]
Convert a b2Vec2 in a QPoint.
Definition at line 21 of file tools.h.
Referenced by Joint::drawLines(), Goo::getPPosition(), Level::mouseMoveEvent(), FixedGoo::paint(), RopeJoint::paint(), BalloonGoo::paint(), StickyLink::paint(), DynamicGoo::paint(), Joint::paintDebug(), FixedGoo::paintDebug(), Level::paintTargetArrow(), CollisionListener::PostSolve(), and Level::timerEvent().
QPolygon toPoly (const QList< QPoint > & ps, QPoint center)
Convert a QList of QPoint in a QPolygon transated of *center*.
Definition at line 10 of file tools.cpp.
Referenced by Ground::Ground(), SvgLevelLoader::parseBackground(), and Thorn::Thorn().
QString time2string (int time)
Definition at line 18 of file tools.cpp.
Referenced by Level::paintScore().